### ISSUE TITLE
More than one callback in `jack.Client.set_process_callback`

### ISSUE THREAD

**Issue by Stemby** [spatialaudio/jackclient-python#101]
Related to #100: can [`jack.Client.set_process_callback`](https://jackclient-python.readthedocs.io/en/0.5.3/api.html#jack.Client.set_process_callback) register more than one process callback?

Thank you!

Carlo

**Comment by C0nsultant** [comment]
Strictly speaking, no. At least not in the way you're thinking about in https://github.com/spatialaudio/jackclient-python/issues/100#issuecomment-725984668.

Since this framework is really just a nice pythonic wrapper around the JACK [API](https://jackaudio.org/api), `Client.set_process_callback()` only [wraps](https://github.com/spatialaudio/jackclient-python/blob/0.5.3/src/jack.py#L806) the corresponding C function [`jack_set_process_callback()`](https://jackaudio.org/api/group__ClientCallbacks.html#gafb5ec9fb4b736606d676c135fb97888b). Every time that function is called, the last registered callback is overwritten.

But there is a pretty easy way to accomplish your goal of calling multiple callbacks per cycle per client. Instead of registering multiple callbacks individually, create a wrapper function around your callbacks and register that as the callback.

```python
# you want these to callbacks to be called on every cycle
def process_first(frames):
    # wörkwörk
	pass

def process_last(frames):
    # wörkwörk
	pass
```

```python
# so instead of
wont_client = jack.Client('wontwork')
wont_client.set_process_callback(process_first)		# will never be called
wont_client.set_process_callback(process_last)		# only this one is actually called
```

```python
# you create a combining callback
def process_all(frames):
	try:
		process_first(frames)
	except jack.CallbackExit:
		# proper handling recommended
		pass 
	try:
		process_last(frames)
	except jack.CallbackExit:
		# proper handling recommended
		pass
```

```python
# and register that one
will_client = jack.Client('willwork')
will_client.set_process_callback(process_all)		# will always call both callbacks in a specific order
```

If you're concerned about performance and do not care about execution order of your sub-callbacks, you can run them asynchronously.

**Comment by Stemby** [comment]
Thank you, @C0nsultant!

**Comment by mgeier** [comment]
The above example uses `pass` as a placeholder, but the "proper handling recommended" should imply that the exception should probably not be swallowed but in many cases it should probably be propagated to the main callback with `raise`.
