### ISSUE TITLE
undefined symbol: Py_InitModule3

### ISSUE THREAD

**Issue by chris-kuhr** [spatialaudio/jackclient-python#43]
Hi *,

I installed with `sudo python3 -m pip install JACK-Client --user`.

If I try to import the module with `import jack`, I see the following error:

```
~ $ python3 midi_ctl.py
Traceback (most recent call last):
File "midi_ctl.py", line 3, in <module>
import jack
ImportError: /usr/local/lib/python3.5/dist-packages/jack.cpython-35m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule3
```

Any ideas?

BR,
Ck

**Comment by mgeier** [comment]
Regarding `pip`: The `--user` option tells `pip` to install the package only for the current user (in the home directory), therefore no `root` access and no `sudo` is required. This may or may not be related to your problem.

It looks like you have another Python module named `jack` installed. Your error message talks about a `.so` file (i.e. a compiled module). This module here doesn't use a compiler, it consists only of the main module file `jack.py` and (since version 0.4.3) an additional file named `_jack.py`.

**Comment by chris-kuhr** [comment]
Ok, thanks.

I removed the other pyjack package and now it's working.

BR,
Ck
