### ISSUE TITLE
install problems related to lib/jack folder

### ISSUE THREAD

**Issue by nedlrichards** [spatialaudio/jackclient-python#68]
If you install jackclient using pip without installing jack first, it becomes hard to fix the problem. To reproduce (i use anaconda, so my pip installs are all local by default).

1) (Without jack installed) `pip install JACK-Client`
2) Woops... `sudo apt install multimedia-jack`
3) (With jack installed) `pip uninstall JACK-Client`
4) (With jack installed) `pip install JACK-Client`

This install mistake brings up a very strange error where find_library returns a directory instead of a library. The ... dots aren't real, just hiding my file system for no particular reason.

```
>>> import jack 
OSError: cannot load library '.../miniconda3/envs/py3/lib/jack'
>>> from ctypes.util import find_library
>>> find_library("jack")
'.../miniconda3/envs/py3/lib/jack'
```

I fixed this eventually by: 
step (3)
deleting the `.../miniconda3/envs/py3/lib/jack` directory
step (4)

Is it possible to delete this directory as a part of the pip uninstall process?

**Comment by mgeier** [comment]
I'm not a `pip` expert, but I don't think it is possible to do any custom actions in the `uninstall` process.

But anyway, this is really strange, because `find_library()` shouldn't ever show a directory, right?

Would you mind asking about this in some Python support forum or mailing list?

And at which point is this directory even created?

**Comment by mgeier** [comment]
@nedlrichards Any news on this?

**Comment by mgeier** [comment]
Closing due to lack of response.
